FROM python:3.10


WORKDIR /mapgen
COPY requeriments.txt /mapgen/requeriments.txt

RUN pip install --no-cache-dir --upgrade -r /mapgen/requeriments.txt

COPY . /mapgen

CMD bash -c "while true; do sleep 1; done"
